Update build-notebooks-TEMPLATE.yaml

diff --git a/.github/workflows/build-notebooks-TEMPLATE.yaml b/.github/workflows/build-notebooks-TEMPLATE.yaml
--- a/.github/workflows/build-notebooks-TEMPLATE.yaml
+++ b/.github/workflows/build-notebooks-TEMPLATE.yaml
@@ -119,11 +119,22 @@ jobs:
           IMAGE_REGISTRY: "localhost:5000/workbench-images"
           CONTAINER_BUILD_CACHE_ARGS: "--cache-from ${{ env.CACHE }}"
 
+      - name: "pull_request: get the name of the image"
+        if: "${{ fromJson(inputs.github).event_name == 'pull_request' }}"
+        id: get_image_name
+        run: |
+          IMAGE_NAME=$(podman images --format '{{.Repository}}:{{.Tag}}' --no-trunc | head -n 1)
+          if [ -z "$IMAGE_NAME" ]; then
+            echo "Failed to get image name"
+            exit 1
+          fi
+          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
+
       - name: "pull_request: Run Trivy vulnerability scanner"
         if: "${{ fromJson(inputs.github).event_name == 'pull_request' }}"
         uses: aquasecurity/trivy-action@7c2007bcb556501da015201bcba5aa14069b74e2  # v0.23.0
         with:
-          image-ref: 'localhost:5000/workbench-images:${{ inputs.target }}-${{ github.sha }}'
+          image-ref: ${{ steps.get_image_name.outputs.image_name }}
           ignore-unfixed: true
 
       - run: df -h
